# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-general

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Get date for tag name
      id: get_date
      run: echo "::set-output name=date::$( date +'%m-%d-%Y' )"

    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a424fdf902254affa2715adc11d7c8e8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1f64a31c122b4a2280b0bfd3e9c5557a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: 425005869/general:${{ steps.get_date.outputs.date }}.${{ github.run_attempt }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-general'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6c39f73fa0de465cae5ec315b61f6b34 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a424fdf902254affa2715adc11d7c8e8 }}/425005869/general:${{ github.sha }}'